[package]
name = "ecs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
hecs = "0.10.4"
wasm-bindgen = "0.2"
console_log = "1.0"
console_error_panic_hook = "0.1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
fastrand = "2.1"